server:
  port: 9090
mqtt:
  host: tcp://127.0.0.1:1234
#  host: tcp://39.99.202.25:1883
  clientinid: ${random.value}
  clientoutid: ${random.value}
  topic: t1,t2,t3,t 4,t5,t6
  qoslevel: 1
  #MQTT 认证
  username: test2
  password: test22020
  # 10stopic
  timeout: 10000
  #20s
  keepalive: 20
